env:
  node: true

parser: babel-eslint

plugins:
  - 'fp'
  - 'jest'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:fp/recommended'

rules:
  no-console: 0
  fp/no-unused-expression: 0 # чтобы не ругался на вызов консоли. TODO: убрать после релиза
