env:
  node: true

parser: babel-eslint

plugins:
  - 'fp'
  - 'jest'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:fp/recommended'

rules:
  no-console: 0
  fp/no-unused-expression: 0 # for console.log use
  fp/no-throw: 0 # for throw use
  fp/no-rest-parameters: 0 # for rest-operations